name: Pull request tests
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: ['zulu']
        java: [ '8', '11','15', '17' ]
    name: Java ${{ matrix.Java }} (${{ matrix.distribution }})
    steps:
      - uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2pull-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2pull

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - run: mvn --batch-mode --update-snapshots test