name: "Tests - Unit"
on: 
  push:
    branches-ignore:
      - main
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2tests-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2tests

    - name: Run tests
      run: |
        mvn \
        clean test