name: Scan container for CVE
on: 
  push:
    branches-ignore:
      - main
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Extract Maven project version
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      id: project

    - name: Build local container image
      run: |
        mvn \
        clean compile jib:dockerBuild

    - name: Scan local container image
      uses: anchore/scan-action@v3
      with:
        image: "registry.hub.docker.com/parjanya/samplespringbootapp:${{ steps.project.outputs.version }}"
        fail-build: true
        severity-cutoff: critical
